export type VendorDef = {
  key: string;
  name: string;
  statusUrl: string;
  parserHint?: "statuspage" | "khoros" | "custom" | "unknown";
  tags?: string[];
};

export const EXTRA_VENDORS: VendorDef[] = [
  {
    key: "connectwise",
    name: "ConnectWise",
    statusUrl: "https://status.connectwise.com/",
    parserHint: "statuspage",
    tags: ["MSP", "IT Ops"],
  },
  {
    key: "kaseya",
    name: "Kaseya",
    statusUrl: "https://status.kaseya.com/",
    parserHint: "statuspage",
    tags: ["MSP", "IT Ops"],
  },
  {
    key: "nable",
    name: "N-able",
    statusUrl: "https://status.n-able.com/",
    parserHint: "custom",
    tags: ["MSP", "IT Ops"],
  },
  {
    key: "syncro",
    name: "Syncro",
    statusUrl: "https://www.syncrostatus.com/",
    parserHint: "custom",
    tags: ["MSP", "IT Ops"],
  },
  {
    key: "sentinelone",
    name: "SentinelOne",
    statusUrl: "https://status.sentinelone.com/",
    parserHint: "statuspage",
    tags: ["Security"],
  },
  {
    key: "auth0",
    name: "Auth0",
    statusUrl: "https://status.auth0.com/",
    parserHint: "statuspage",
    tags: ["Identity", "Auth"],
  },
  {
    key: "pingidentity",
    name: "Ping Identity",
    statusUrl: "https://status.pingidentity.com/",
    parserHint: "custom",
    tags: ["Identity", "Auth"],
  },
  {
    key: "slack",
    name: "Slack",
    statusUrl: "https://slack-status.com/",
    parserHint: "custom",
    tags: ["SaaS", "Collaboration"],
  },
  {
    key: "hubspot",
    name: "HubSpot",
    statusUrl: "https://status.hubspot.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "CRM"],
  },
  {
    key: "quickbooks",
    name: "QuickBooks Online",
    statusUrl: "https://status.quickbooks.intuit.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Finance"],
  },
  {
    key: "netsuite",
    name: "Oracle NetSuite",
    statusUrl: "https://status.netsuite.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "ERP", "Finance"],
  },
  {
    key: "fastly",
    name: "Fastly",
    statusUrl: "https://www.fastlystatus.com/",
    parserHint: "custom",
    tags: ["CDN", "Edge"],
  },
  {
    key: "akamai",
    name: "Akamai",
    statusUrl: "https://www.akamaistatus.com/",
    parserHint: "statuspage",
    tags: ["CDN", "Edge"],
  },
  {
    key: "veeam_datacloud",
    name: "Veeam Data Cloud",
    statusUrl: "https://vdcstatus.veeam.com/",
    parserHint: "custom",
    tags: ["Backup", "Data Protection"],
  },
  {
    key: "fireblocks",
    name: "Fireblocks",
    statusUrl: "https://status.fireblocks.com/",
    parserHint: "unknown",
    tags: ["Crypto", "Custody", "Payments"],
  },
  {
    key: "vercel",
    name: "Vercel",
    statusUrl: "https://www.vercel-status.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Hosting"],
  },
  {
    key: "netlify",
    name: "Netlify",
    statusUrl: "https://www.netlifystatus.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Hosting"],
  },
  {
    key: "render",
    name: "Render",
    statusUrl: "https://status.render.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Cloud"],
  },
  {
    key: "railway",
    name: "Railway",
    statusUrl: "https://status.railway.app/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Cloud"],
  },
  {
    key: "supabase",
    name: "Supabase",
    statusUrl: "https://status.supabase.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Database"],
  },
  {
    key: "prisma",
    name: "Prisma",
    statusUrl: "https://status.prisma.io/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Database"],
  },
  {
    key: "postman",
    name: "Postman",
    statusUrl: "https://status.postman.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "API"],
  },
  {
    key: "circleci",
    name: "CircleCI",
    statusUrl: "https://status.circleci.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CI/CD"],
  },
  {
    key: "travisci",
    name: "Travis CI",
    statusUrl: "https://www.traviscistatus.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CI/CD"],
  },
  {
    key: "jfrog",
    name: "JFrog",
    statusUrl: "https://status.jfrog.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CI/CD"],
  },
  {
    key: "contentful",
    name: "Contentful",
    statusUrl: "https://www.contentfulstatus.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CMS"],
  },
  {
    key: "sanity",
    name: "Sanity",
    statusUrl: "https://status.sanity.io/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CMS"],
  },
  {
    key: "storyblok",
    name: "Storyblok",
    statusUrl: "https://status.storyblok.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CMS"],
  },
  {
    key: "sentry",
    name: "Sentry",
    statusUrl: "https://status.sentry.io/",
    parserHint: "statuspage",
    tags: ["Monitoring", "Developer Tools"],
  },
  {
    key: "snyk",
    name: "Snyk",
    statusUrl: "https://status.snyk.io/",
    parserHint: "statuspage",
    tags: ["Security", "Developer Tools"],
  },
  {
    key: "sonarcloud",
    name: "SonarCloud",
    statusUrl: "https://sonarcloud.statuspage.io/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Code Quality"],
  },
  {
    key: "openai",
    name: "OpenAI",
    statusUrl: "https://status.openai.com/",
    parserHint: "statuspage",
    tags: ["AI", "API"],
  },
  {
    key: "anthropic",
    name: "Anthropic",
    statusUrl: "https://status.anthropic.com/",
    parserHint: "statuspage",
    tags: ["AI", "API"],
  },
  {
    key: "notion",
    name: "Notion",
    statusUrl: "https://status.notion.so/",
    parserHint: "statuspage",
    tags: ["SaaS", "Collaboration"],
  },
  {
    key: "linear",
    name: "Linear",
    statusUrl: "https://status.linear.app/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Project Management"],
  },
  {
    key: "airtable",
    name: "Airtable",
    statusUrl: "https://status.airtable.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Collaboration"],
  },
  {
    key: "flyio",
    name: "Fly.io",
    statusUrl: "https://status.flyio.net/",
    parserHint: "statuspage",
    tags: ["Cloud", "Hosting"],
  },
  {
    key: "mongodb",
    name: "MongoDB Atlas",
    statusUrl: "https://status.cloud.mongodb.com/",
    parserHint: "statuspage",
    tags: ["Cloud", "Database"],
  },
  {
    key: "elastic",
    name: "Elastic Cloud",
    statusUrl: "https://status.elastic.co/",
    parserHint: "statuspage",
    tags: ["Cloud", "Search"],
  },
  {
    key: "confluent",
    name: "Confluent",
    statusUrl: "https://status.confluent.cloud/",
    parserHint: "statuspage",
    tags: ["Cloud", "Streaming"],
  },
  {
    key: "onepassword",
    name: "1Password",
    statusUrl: "https://status.1password.com/",
    parserHint: "statuspage",
    tags: ["Security", "Identity"],
  },
  {
    key: "lastpass",
    name: "LastPass",
    statusUrl: "https://status.lastpass.com/",
    parserHint: "statuspage",
    tags: ["Security", "Identity"],
  },
  {
    key: "coinbase",
    name: "Coinbase",
    statusUrl: "https://status.coinbase.com/",
    parserHint: "statuspage",
    tags: ["Crypto", "Payments"],
  },
  {
    key: "shopify",
    name: "Shopify",
    statusUrl: "https://status.shopify.com/",
    parserHint: "statuspage",
    tags: ["E-Commerce", "SaaS"],
  },
  {
    key: "asana",
    name: "Asana",
    statusUrl: "https://trust.asana.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Project Management"],
  },
  {
    key: "trello",
    name: "Trello",
    statusUrl: "https://trello.status.atlassian.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Project Management"],
  },
  {
    key: "docusign",
    name: "DocuSign",
    statusUrl: "https://status.docusign.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Productivity"],
  },
  {
    key: "adobe",
    name: "Adobe Creative Cloud",
    statusUrl: "https://status.adobe.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "Productivity"],
  },
  {
    key: "twilio",
    name: "Twilio",
    statusUrl: "https://status.twilio.com/",
    parserHint: "statuspage",
    tags: ["Communication", "API"],
  },
  {
    key: "sendgrid",
    name: "SendGrid",
    statusUrl: "https://status.sendgrid.com/",
    parserHint: "statuspage",
    tags: ["Communication", "Email"],
  },
  {
    key: "hashicorp",
    name: "HashiCorp",
    statusUrl: "https://status.hashicorp.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Cloud"],
  },
  {
    key: "launchdarkly",
    name: "LaunchDarkly",
    statusUrl: "https://status.launchdarkly.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Feature Flags"],
  },
  {
    key: "algolia",
    name: "Algolia",
    statusUrl: "https://status.algolia.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Search"],
  },
  {
    key: "docker",
    name: "Docker",
    statusUrl: "https://www.dockerstatus.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Containers"],
  },
  {
    key: "cloudinary",
    name: "Cloudinary",
    statusUrl: "https://status.cloudinary.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Media"],
  },
  {
    key: "mapbox",
    name: "Mapbox",
    statusUrl: "https://status.mapbox.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Maps"],
  },
  {
    key: "cockroachdb",
    name: "CockroachDB",
    statusUrl: "https://status.cockroachlabs.cloud/",
    parserHint: "statuspage",
    tags: ["Cloud", "Database"],
  },
  {
    key: "planetscale",
    name: "PlanetScale",
    statusUrl: "https://www.planetscalestatus.com/",
    parserHint: "statuspage",
    tags: ["Cloud", "Database"],
  },
  {
    key: "neon",
    name: "Neon",
    statusUrl: "https://neonstatus.com/",
    parserHint: "statuspage",
    tags: ["Cloud", "Database"],
  },
  {
    key: "grafana",
    name: "Grafana Cloud",
    statusUrl: "https://status.grafana.com/",
    parserHint: "statuspage",
    tags: ["Monitoring", "Observability"],
  },
  {
    key: "deno",
    name: "Deno Deploy",
    statusUrl: "https://www.denostatus.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Hosting"],
  },
  {
    key: "upstash",
    name: "Upstash",
    statusUrl: "https://status.upstash.com/",
    parserHint: "statuspage",
    tags: ["Cloud", "Database"],
  },
  {
    key: "wix",
    name: "Wix",
    statusUrl: "https://www.wixstatus.com/",
    parserHint: "statuspage",
    tags: ["SaaS", "E-Commerce"],
  },
  {
    key: "webflow",
    name: "Webflow",
    statusUrl: "https://status.webflow.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CMS"],
  },
  {
    key: "ghost",
    name: "Ghost",
    statusUrl: "https://status.ghost.org/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "CMS"],
  },
  {
    key: "retool",
    name: "Retool",
    statusUrl: "https://status.retool.com/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Low-Code"],
  },
  {
    key: "expo",
    name: "Expo",
    statusUrl: "https://status.expo.dev/",
    parserHint: "statuspage",
    tags: ["Developer Tools", "Mobile"],
  },
];

export function dedupeVendorsByKey<T extends { key: string }>(vendors: T[]): T[] {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const v of vendors) {
    const k = (v.key || "").trim().toLowerCase();
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(v);
  }
  return out;
}
